image: alpine/edge
packages:
  - hut
  - nodejs
  - npm
oauth: pages.sr.ht/PAGES:RW
secrets:
  - 67becea4-daae-4df9-8a7a-f2d83ac33b01
environment:
  site: klara-sun.srht.site
sources:
  - git@git.sr.ht:~dokoissho/digital-garden#v4
tasks:
  - build: |
      cd digital-garden
      npm ci
      npx quartz build
  - package: |
      cd digital-garden
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
